debug: false
uuid: e0979cb7-a79d-4dfc-8901-fad3a70895ac
token_id: IWfvueqyj0BSJRMT
token: LiZazRaBrqHpgWHZhoIRJqIYgdW1rRlYQUfUu3Xxib2Z3MX72K3kahDvW7MLdZWJ
api:
  host: 0.0.0.0
  port: 51232
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/yuluknodes.us.to/fullchain.pem
    key: /etc/letsencrypt/live/yuluknodes.us.to/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://yuluknodes.us.to:51231'
