debug: false
uuid: a2a77769-82bd-4d47-9638-176b5f98acc2
token_id: 7eO8gK1MrmKOFW4e
token: ADkxBiVhfLG69jNzN9d8dhWx82Y0wWbrsasmZJSwTw2oMdNRn6G5d2ZOsbUq4L3a
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/eagerly-promoted-lobster.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/eagerly-promoted-lobster.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://grown-dogfish-liberal.ngrok-free.app'
